services:
  api:
    image: sg-librechat-task2e:local
    build:
      context: .
      dockerfile: Dockerfile
    ports: !override
      - "5080:3080"
    environment:
      SG_GATEWAY_API_KEY: ${SG_GATEWAY_API_KEY}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
        read_only: true
