server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location ~ /\. {
    deny all;
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Access-Control-Allow-Origin "*" always;
    add_header Cache-Control "public, max-age=86400, immutable" always;
    add_header Service-Worker-Allowed "/" always;
    add_header X-Content-Type-Options "nosniff" always;
  }
}
